In [1]:
import pandas as pd

In [2]:
iris = pd.read_csv('../datasets/iris.csv')

In [3]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df = iris.drop('species', axis=1)

In [5]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

### Build the model

In [6]:
from sklearn.cluster import DBSCAN

In [7]:
model = DBSCAN(min_samples=12, eps=0.5 )

In [8]:
model.fit(df)

DBSCAN(min_samples=12)

In [9]:
model.labels_

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0, -1,
        1, -1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1, -1,  1,
       -1,  2,  2, -1, -1, -1, -1, -1,  2,  2,  2, -1, -1,  2,  2, -1, -1,
       -1,  2, -1, -1,  1,  2, -1,  1,  1,  2, -1, -1, -1,  2,  1, -1, -1,
       -1,  2,  1,  2,  2,  2,  1,  2, -1,  2,  1,  2, -1,  1])

In [10]:
iris['Label'] = model.labels_

In [ ]:
iris._get_numeric_data

In [12]:
iris

     sepal_length  sepal_width  petal_length  petal_width    species  Label
0             5.1          3.5           1.4          0.2     setosa      0
1             4.9          3.0           1.4          0.2     setosa      0
2             4.7          3.2           1.3          0.2     setosa      0
3             4.6          3.1           1.5          0.2     setosa      0
4             5.0          3.6           1.4          0.2     setosa      0
..            ...          ...           ...          ...        ...    ...
145           6.7          3.0           5.2          2.3  virginica      2
146           6.3          2.5           5.0          1.9  virginica      1
147           6.5          3.0           5.2          2.0  virginica      2
148           6.2          3.4           5.4          2.3  virginica     -1
149           5.9          3.0           5.1          1.8  virginica      1

[150 rows x 6 columns]

In [14]:
grp = iris.groupby('Label')

In [16]:
for x,y in grp:
    print(y)
    print('_'*70)

     sepal_length  sepal_width  petal_length  petal_width     species  Label
14            5.8          4.0           1.2          0.2      setosa     -1
15            5.7          4.4           1.5          0.4      setosa     -1
33            5.5          4.2           1.4          0.2      setosa     -1
41            4.5          2.3           1.3          0.3      setosa     -1
50            7.0          3.2           4.7          1.4  versicolor     -1
52            6.9          3.1           4.9          1.5  versicolor     -1
57            4.9          2.4           3.3          1.0  versicolor     -1
60            5.0          2.0           3.5          1.0  versicolor     -1
68            6.2          2.2           4.5          1.5  versicolor     -1
87            6.3          2.3           4.4          1.3  versicolor     -1
93            5.0          2.3           3.3          1.0  versicolor     -1
98            5.1          2.5           3.0          1.1  versicolor     -1
100           6.3          3.3           6.0          2.5   virginica     -1
102           7.1          3.0           5.9          2.1   virginica     -1
105           7.6          3.0           6.6          2.1   virginica     -1
106           4.9          2.5           4.5          1.7   virginica     -1
107           7.3          2.9           6.3          1.8   virginica     -1
108           6.7          2.5           5.8          1.8   virginica     -1
109           7.2          3.6           6.1          2.5   virginica     -1
113           5.7          2.5           5.0          2.0   virginica     -1
114           5.8          2.8           5.1          2.4   virginica     -1
117           7.7          3.8           6.7          2.2   virginica     -1
118           7.7          2.6           6.9          2.3   virginica     -1
119           6.0          2.2           5.0          1.5   virginica     -1
121           5.6          2.8           4.9          2.0   virginica     -1
122           7.7          2.8           6.7          2.0   virginica     -1
125           7.2          3.2           6.0          1.8   virginica     -1
129           7.2          3.0           5.8          1.6   virginica     -1
130           7.4          2.8           6.1          1.9   virginica     -1
131           7.9          3.8           6.4          2.0   virginica     -1
134           6.1          2.6           5.6          1.4   virginica     -1
135           7.7          3.0           6.1          2.3   virginica     -1
136           6.3          3.4           5.6          2.4   virginica     -1
144           6.7          3.3           5.7          2.5   virginica     -1
148           6.2          3.4           5.4          2.3   virginica     -1
______________________________________________________________________
    sepal_length  sepal_width  petal_length  petal_width species  Label
0            5.1          3.5           1.4          0.2  setosa      0
1            4.9          3.0           1.4          0.2  setosa      0
2            4.7          3.2           1.3          0.2  setosa      0
3            4.6          3.1           1.5          0.2  setosa      0
4            5.0          3.6           1.4          0.2  setosa      0
5            5.4          3.9           1.7          0.4  setosa      0
6            4.6          3.4           1.4          0.3  setosa      0
7            5.0          3.4           1.5          0.2  setosa      0
8            4.4          2.9           1.4          0.2  setosa      0
9            4.9          3.1           1.5          0.1  setosa      0
10           5.4          3.7           1.5          0.2  setosa      0
11           4.8          3.4           1.6          0.2  setosa      0
12           4.8          3.0           1.4          0.1  setosa      0
13           4.3          3.0           1.1          0.1  setosa      0
16           5.4          3.9           1.3          0.4  setosa      0
17           5.1          3.5           1.4          0.3  setosa      0
18           5.7          3.8           1.7          0.3  setosa      0
19           5.1          3.8           1.5          0.3  setosa      0
20           5.4          3.4           1.7          0.2  setosa      0
21           5.1          3.7           1.5          0.4  setosa      0
22           4.6          3.6           1.0          0.2  setosa      0
23           5.1          3.3           1.7          0.5  setosa      0
24           4.8          3.4           1.9          0.2  setosa      0
25           5.0          3.0           1.6          0.2  setosa      0
26           5.0          3.4           1.6          0.4  setosa      0
27           5.2          3.5           1.5          0.2  setosa      0
28           5.2          3.4           1.4          0.2  setosa      0
29           4.7          3.2           1.6          0.2  setosa      0
30           4.8          3.1           1.6          0.2  setosa      0
31           5.4          3.4           1.5          0.4  setosa      0
32           5.2          4.1           1.5          0.1  setosa      0
34           4.9          3.1           1.5          0.2  setosa      0
35           5.0          3.2           1.2          0.2  setosa      0
36           5.5          3.5           1.3          0.2  setosa      0
37           4.9          3.6           1.4          0.1  setosa      0
38           4.4          3.0           1.3          0.2  setosa      0
39           5.1          3.4           1.5          0.2  setosa      0
40           5.0          3.5           1.3          0.3  setosa      0
42           4.4          3.2           1.3          0.2  setosa      0
43           5.0          3.5           1.6          0.6  setosa      0
44           5.1          3.8           1.9          0.4  setosa      0
45           4.8          3.0           1.4          0.3  setosa      0
46           5.1          3.8           1.6          0.2  setosa      0
47           4.6          3.2           1.4          0.2  setosa      0
48           5.3          3.7           1.5          0.2  setosa      0
49           5.0          3.3           1.4          0.2  setosa      0
______________________________________________________________________
     sepal_length  sepal_width  petal_length  petal_width     species  Label
51            6.4          3.2           4.5          1.5  versicolor      1
53            5.5          2.3           4.0          1.3  versicolor      1
54            6.5          2.8           4.6          1.5  versicolor      1
55            5.7          2.8           4.5          1.3  versicolor      1
56            6.3          3.3           4.7          1.6  versicolor      1
58            6.6          2.9           4.6          1.3  versicolor      1
59            5.2          2.7           3.9          1.4  versicolor      1
61            5.9          3.0           4.2          1.5  versicolor      1
62            6.0          2.2           4.0          1.0  versicolor      1
63            6.1          2.9           4.7          1.4  versicolor      1
64            5.6          2.9           3.6          1.3  versicolor      1
65            6.7          3.1           4.4          1.4  versicolor      1
66            5.6          3.0           4.5          1.5  versicolor      1
67            5.8          2.7           4.1          1.0  versicolor      1
69            5.6          2.5           3.9          1.1  versicolor      1
70            5.9          3.2           4.8          1.8  versicolor      1
71            6.1          2.8           4.0          1.3  versicolor      1
72            6.3          2.5           4.9          1.5  versicolor      1
73            6.1          2.8           4.7          1.2  versicolor      1
74            6.4          2.9           4.3          1.3  versicolor      1
75            6.6          3.0           4.4          1.4  versicolor      1
76            6.8          2.8           4.8          1.4  versicolor      1
78            6.0          2.9           4.5          1.5  versicolor      1
79            5.7          2.6           3.5          1.0  versicolor      1
80            5.5          2.4           3.8          1.1  versicolor      1
81            5.5          2.4           3.7          1.0  versicolor      1
82            5.8          2.7           3.9          1.2  versicolor      1
83            6.0          2.7           5.1          1.6  versicolor      1
84            5.4          3.0           4.5          1.5  versicolor      1
85            6.0          3.4           4.5          1.6  versicolor      1
86            6.7          3.1           4.7          1.5  versicolor      1
88            5.6          3.0           4.1          1.3  versicolor      1
89            5.5          2.5           4.0          1.3  versicolor      1
90            5.5          2.6           4.4          1.2  versicolor      1
91            6.1          3.0           4.6          1.4  versicolor      1
92            5.8          2.6           4.0          1.2  versicolor      1
94            5.6          2.7           4.2          1.3  versicolor      1
95            5.7          3.0           4.2          1.2  versicolor      1
96            5.7          2.9           4.2          1.3  versicolor      1
97            6.2          2.9           4.3          1.3  versicolor      1
99            5.7          2.8           4.1          1.3  versicolor      1
101           5.8          2.7           5.1          1.9   virginica      1
123           6.3          2.7           4.9          1.8   virginica      1
126           6.2          2.8           4.8          1.8   virginica      1
127           6.1          3.0           4.9          1.8   virginica      1
133           6.3          2.8           5.1          1.5   virginica      1
138           6.0          3.0           4.8          1.8   virginica      1
142           5.8          2.7           5.1          1.9   virginica      1
146           6.3          2.5           5.0          1.9   virginica      1
149           5.9          3.0           5.1          1.8   virginica      1
______________________________________________________________________
     sepal_length  sepal_width  petal_length  petal_width     species  Label
77            6.7          3.0           5.0          1.7  versicolor      2
103           6.3          2.9           5.6          1.8   virginica      2
104           6.5          3.0           5.8          2.2   virginica      2
110           6.5          3.2           5.1          2.0   virginica      2
111           6.4          2.7           5.3          1.9   virginica      2
112           6.8          3.0           5.5          2.1   virginica      2
115           6.4          3.2           5.3          2.3   virginica      2
116           6.5          3.0           5.5          1.8   virginica      2
120           6.9          3.2           5.7          2.3   virginica      2
124           6.7          3.3           5.7          2.1   virginica      2
128           6.4          2.8           5.6          2.1   virginica      2
132           6.4          2.8           5.6          2.2   virginica      2
137           6.4          3.1           5.5          1.8   virginica      2
139           6.9          3.1           5.4          2.1   virginica      2
140           6.7          3.1           5.6          2.4   virginica      2
141           6.9          3.1           5.1          2.3   virginica      2
143           6.8          3.2           5.9          2.3   virginica      2
145           6.7          3.0           5.2          2.3   virginica      2
147           6.5          3.0           5.2          2.0   virginica      2
______________________________________________________________________

In [17]:
grp.agg('mean')

       sepal_length  sepal_width  petal_length  petal_width
Label
-1         6.397143     2.962857      4.891429     1.657143
 0         4.973913     3.402174      1.471739     0.243478
 1         5.968000     2.814000      4.424000     1.420000
 2         6.600000     3.036842      5.452632     2.089474

In [18]:
sgrp = iris.groupby('species')

In [19]:
sgrp.agg('mean')

            sepal_length  sepal_width  petal_length  petal_width  Label
species
setosa             5.006        3.428         1.462        0.246  -0.08
versicolor         5.936        2.770         4.260        1.326   0.70
virginica          6.588        2.974         5.552        2.026   0.44

In [20]:
from sklearn.metrics import silhouette_score

In [21]:
silhouette_score(df, iris['species'])

0.5034774406932964